#coding=utf-8
__author__ = 'TomasLiu'

CATEGREY_WEIGHT = 3
SUBCATEGREY_WEIGHT = 1
TYPE_SCOER_WEIGET = 5
MODE_WEIGHT = 2

type_map = {
    1: ("川菜", CATEGREY_WEIGHT),
    2: ("香锅", SUBCATEGREY_WEIGHT),
    3: ("烤鱼", SUBCATEGREY_WEIGHT),
    4: ("粤菜", CATEGREY_WEIGHT),
    5: ("茶餐厅", SUBCATEGREY_WEIGHT),
    6: ("燕翅鲍", SUBCATEGREY_WEIGHT),
    7: ("潮汕菜", SUBCATEGREY_WEIGHT),
    8: ("江浙菜", CATEGREY_WEIGHT),
    9: ("淮扬菜", SUBCATEGREY_WEIGHT),
    10: ("上海菜", SUBCATEGREY_WEIGHT),
    11: ("浙江菜", SUBCATEGREY_WEIGHT),
    12: ("火锅", CATEGREY_WEIGHT),
    13: ("小火锅", SUBCATEGREY_WEIGHT),
    14: ("重庆火锅", SUBCATEGREY_WEIGHT),
    15: ("涮羊肉", SUBCATEGREY_WEIGHT),
    16: ("串串香", SUBCATEGREY_WEIGHT),
    17: ("羊蝎子", SUBCATEGREY_WEIGHT),
    18: ("鱼火锅", SUBCATEGREY_WEIGHT),
    19: ("自助餐", CATEGREY_WEIGHT),
    20: ("清真菜", CATEGREY_WEIGHT),
    21: ("素菜", CATEGREY_WEIGHT),
    22: ("东北菜", CATEGREY_WEIGHT),
    23: ("湘菜", CATEGREY_WEIGHT),
    24: ("贵州菜", CATEGREY_WEIGHT),
    25: ("面包甜点", CATEGREY_WEIGHT),
    26: ("冰淇淋", SUBCATEGREY_WEIGHT),
    27: ("甜品饮品", SUBCATEGREY_WEIGHT),
    28: ("西餐", CATEGREY_WEIGHT),
    29: ("比萨", CATEGREY_WEIGHT),
    30: ("西式简餐", SUBCATEGREY_WEIGHT),
    31: ("意大利菜", SUBCATEGREY_WEIGHT),
    32: ("法国菜", SUBCATEGREY_WEIGHT),
    33: ("牛排", SUBCATEGREY_WEIGHT),
    34: ("拉美烧烤", SUBCATEGREY_WEIGHT),
    35: ("俄罗斯菜", SUBCATEGREY_WEIGHT),
    36: ("东南亚菜", CATEGREY_WEIGHT),
    37: ("越南菜", SUBCATEGREY_WEIGHT),
    38: ("印度菜", SUBCATEGREY_WEIGHT),
    39: ("泰国菜", SUBCATEGREY_WEIGHT),
    40: ("韩国料理", CATEGREY_WEIGHT),
    41: ("日本", CATEGREY_WEIGHT),
    42: ("日式自助", SUBCATEGREY_WEIGHT),
    43: ("寿司/简餐", SUBCATEGREY_WEIGHT),
    44: ("日式烧烤/铁板烧", SUBCATEGREY_WEIGHT),
    45: ("日本料理", SUBCATEGREY_WEIGHT),
    46: ("小吃快餐", CATEGREY_WEIGHT),
    47: ("麻辣烫", SUBCATEGREY_WEIGHT),
    48: ("熟食", SUBCATEGREY_WEIGHT),
    49: ("零食", SUBCATEGREY_WEIGHT),
    50: ("小龙虾", SUBCATEGREY_WEIGHT),
    51: ("馄饨", SUBCATEGREY_WEIGHT),
    52: ("快餐简餐", SUBCATEGREY_WEIGHT),
    53: ("生煎/锅贴", SUBCATEGREY_WEIGHT),
    54: ("包子", SUBCATEGREY_WEIGHT),
    55: ("粥店", SUBCATEGREY_WEIGHT),
    56: ("饺子", SUBCATEGREY_WEIGHT),
    57: ("粉面馆", SUBCATEGREY_WEIGHT),
    58: ("老北京小吃", SUBCATEGREY_WEIGHT),
    59: ("炸酱面", SUBCATEGREY_WEIGHT),
    60: ("新疆菜", CATEGREY_WEIGHT),
    61: ("家常菜", CATEGREY_WEIGHT),
    62: ("海鲜", CATEGREY_WEIGHT),
    63: ("云南菜", CATEGREY_WEIGHT),
    64: ("湖北菜", CATEGREY_WEIGHT),
    65: ("北京菜", CATEGREY_WEIGHT),
    66: ("官府菜", SUBCATEGREY_WEIGHT),
    67: ("烤鸭", SUBCATEGREY_WEIGHT),
    68: ("鲁菜", CATEGREY_WEIGHT),
    69: ("西北菜", CATEGREY_WEIGHT),
    70: ("烧烤", CATEGREY_WEIGHT),
    71: ("咖啡厅", CATEGREY_WEIGHT),

    101: ("备受好评", TYPE_SCOER_WEIGET),
    102: ("服务热情", TYPE_SCOER_WEIGET),
    103: ("环境雅致", TYPE_SCOER_WEIGET),
    104: ("气氛热闹", TYPE_SCOER_WEIGET),
    105: ("菜品精致", TYPE_SCOER_WEIGET),
    106: ("菜式新颖", TYPE_SCOER_WEIGET),
    107: ("经济实惠", TYPE_SCOER_WEIGET),
    108: ("地道正宗", TYPE_SCOER_WEIGET),
    109: ("交通便捷", TYPE_SCOER_WEIGET),
    110: ("无需等位", TYPE_SCOER_WEIGET),
    111: ("免费wifi", TYPE_SCOER_WEIGET),
    112: ("无限畅饮", TYPE_SCOER_WEIGET),

    151: ("休闲小憩", MODE_WEIGHT),
    152: ("朋友聚会", MODE_WEIGHT),
    153: ("情侣约会", MODE_WEIGHT),
    154: ("吃喝玩乐", MODE_WEIGHT),
    155: ("烛光晚餐", MODE_WEIGHT),
    156: ("高端奢华", MODE_WEIGHT),
    157: ("嗨到天明", MODE_WEIGHT),
    158: ("家庭聚会", MODE_WEIGHT)
}

type_reverse_map = {
     "川菜" : 1 ,
     "香锅": 2 ,
     "烤鱼": 3 ,
     "粤菜": 4 ,
     "茶餐厅": 5 ,
     "燕翅鲍": 6 ,
     "潮汕菜": 7 ,
     "江浙菜": 8 ,
     "淮扬菜": 9 ,
     "上海菜": 10,
     "浙江菜": 11,
     "火锅": 12,
     "小火锅": 13,
     "重庆火锅": 14,
     "涮羊肉": 15,
     "串串香": 16,
     "羊蝎子": 17,
     "鱼火锅": 18,
     "自助餐": 19,
     "清真菜": 20,
     "素菜": 21,
     "东北菜": 22,
     "湘菜": 23,
     "贵州菜": 24,
     "面包甜点": 25,
     "冰淇淋": 26,
     "甜品饮品": 27,
     "西餐": 28,
     "比萨": 29,
     "西式简餐": 30,
     "意大利菜": 31,
     "法国菜": 32,
     "牛排": 33,
     "拉美烧烤": 34,
     "俄罗斯菜": 35,
     "东南亚菜": 36,
     "越南菜": 37,
     "印度菜": 38,
     "泰国菜": 39,
     "韩国料理": 40,
     "日本": 41,
     "日式自助": 42,
     "寿司/简餐": 43,
     "日式烧烤/铁板烧": 44,
     "日本料理": 45,
     "小吃快餐": 46,
     "麻辣烫": 47,
     "熟食": 48,
     "零食": 49,
     "小龙虾": 50,
     "馄饨": 51,
     "快餐简餐": 52,
     "生煎/锅贴": 53,
     "包子": 54,
     "粥店": 55,
     "饺子": 56,
     "粉面馆": 57,
     "老北京小吃": 58,
     "炸酱面": 59,
     "新疆菜": 60,
     "家常菜": 61,
     "海鲜": 62,
     "云南菜": 63,
     "湖北菜": 64,
     "北京菜": 65,
     "官府菜": 66,
     "烤鸭": 67,
     "鲁菜": 68,
     "西北菜": 69,
     "烧烤": 70,
     "咖啡厅": 71,

    "备受好评": 101,
    "服务热情": 102,
    "环境雅致": 103,
    "气氛热闹": 104,
    "菜品精致": 105,
    "菜式新颖": 106,
    "经济实惠": 107,
    "地道正宗": 108,
    "交通便捷": 109,
    "无需等位": 110,
    "免费wifi": 111,
    "无限畅饮": 112,

    "休闲小憩": 151,
    "朋友聚会": 152,
    "情侣约会": 153,
    "吃喝玩乐": 154,
    "烛光晚餐": 155,
    "高端奢华": 156,
    "嗨到天明": 157,
    "家庭聚会": 158
}
